default_realm: ldap
realms:
    ldap:
        credential:
            class: Password
            password_field: password
            password_type:  self_check
        store:
            class: LDAP
            ldap_server: [% LDAP_URI %]
            ldap_server_options:
                timeout: 30
            binddn: [% LDAP_BINDDN %]
            bindpw: [% LDAP_BINDPW %]
            start_tls: 0
            start_tls_options:
                verify: none
            user_basedn: ou=People,[% LDAP_BASEDN %]
            user_filter: (&(objectClass=posixAccount)(uid=%s))
            user_scope: one
            user_field: uid
            user_search_options:
                deref: always
            use_roles: 0
            role_basedn: ou=groups,[% LDAP_BASEDN %]
            role_filter: (&(objectClass=groupofUniqueNames)(uniqueMember=%s))
            role_scope: one
            role_field: uid
            role_value: dn
            role_search_options:
                deref: always
