order:
  administrator:
    - Help
    - Logout
  user:
    - Sign
    - Logout
    - Help
forms:
  new_root_ca:
    legend: Create New CA
    fields:
      - name: ca-nickname
        prompt: Name:
        type: text
        size: 20
      - name: ca-country
        prompt: Country:
        type: text
        size: 20
      - name: ca-state
        prompt: State:
        type: text
        size: 20
      - name: ca-localitiy
        prompt: Locality:
        type: text
        size: 20
      - name: ca-org
        prompt: Organization:
        type: text
        size: 20
      - name: ca-orgunit
        prompt: Organizational Unit:
        type: text
        size: 20
      - name: ca-email
        prompt: Email:
        type: text
        size: 20
      - name: update_cert_info
        prompt: ~
        type: submit
        value : Update
openssl_cnf_prefs: 
    legend: OpenSSL Preferences
    fields:
      - name: ca_default_days
        prompt: CA Certificate lifetime (days)
        type: text
        size: 20
      - name: crl_days
        prompt: Certificate Revocation List Expires Every (days)
        type: text
        size: 20
  URIs:
    legend: URIs
    fields:
      - name: ca-crt
        prompt: Certificate Authority:
        type: text
        size: 30
      - name: ca-crl
        prompt: Certificate Revocation List:
        type: text
        size: 30
      - name: update_cert_paths
        prompt: ~
        type: submit
        value : Update
  Create:
    legend: Create
    fields:
      - name: newcert-name
        prompt: Certificate Name:
        type: text
        size: 30
      - name: create 
        prompt: ~
        type: submit
        value: Create
  Sign:
    legend: Sign
    fields:
      - name: csr
        prompt: Certificate Signing Request
        type: file
        size: 20
      - name: sign
        prompt: ~
        type: submit
        value: Sign
  Revoke:
    legend: Revoke
    fields:
      - name: revoke
        prompt: ~
        type: submit
        value: Revoke
  Logout: 
    legend: Logout
    fields:
      - name: logout
        prompt: ~
        type: submit
        value: Logout
  Help: 
    legend: Help
    comments: |
      Select something from the tree in the left-pane to do something useful...
  Domain:
    legend: Domain Name
    fields:
      - name: domain
        prompt: Domain Name:
        type: text
        size: 20
      - name: set_domain
        prompt: ~
        type: submit
        value : Set
  Unlock:
    legend: Passphrase
    fields:
      - name: passphrase
        prompt: Passprhase:
        type: password
        size: 20
      - name: unlock_store
        prompt: ~
        type: submit
        value : Unlock
