forms:
  new_root_ca:
    legend: Create New Root Certificate Authority
    fields:
      - name: ca_domain
        prompt: Common Name:
        type: text
        width: 20
        value: example.org
      - name: ca_email
        prompt: Email:
        type: text
        width: 20
        value: sysadmins@example.org
      - name: ca_orgunit
        prompt: Organizational Unit:
        type: text
        width: 20
        value: your department
      - name: ca_org
        prompt: Organization:
        type: text
        width: 20
        value: your company
      - name: ca_localitiy
        prompt: Locality:
        type: text
        width: 20
        value: Nashville
      - name: ca_state
        prompt: State:
        type: text
        width: 20
        value: Tennessee
      - name: ca_country
        prompt: Country:
        type: text
        width: 20
        value: US
      - name: ca_default_days
        prompt: CA Certificate Lifetime (days)
        type: text
        width: 20
        value: 3650
      - name: crl_path
        prompt: Certificate Revocation List URI
        type: text
        width: 40
        value: "http://pki.example.org/example.org.crl"
      - name: crl_days
        prompt: Certificate Revocation List Expires Every (days)
        type: text
        width: 20
        value: 30
      - name: action_type
        prompt: ~
        type: hidden
        value : new_ca
      - name: update_cert_info
        prompt: ~
        type: submit
        value : Create
  new_mid_ca:
    legend: Create New Intermediate Certificate Authority
    fields:
      - name: ca_domain
        prompt: Common Name:
        type: text
        width: 20
      - name: ca_email
        prompt: Email:
        type: text
        width: 20
      - name: ca_orgunit
        prompt: Organizational Unit:
        type: text
        width: 20
      - name: ca_org
        prompt: Organization:
        type: text
        width: 20
      - name: ca_localitiy
        prompt: Locality:
        type: text
        width: 20
      - name: ca_state
        prompt: State:
        type: text
        width: 20
      - name: ca_country
        prompt: Country:
        type: text
        width: 20
      - name: ca_default_days
        prompt: CA Certificate Lifetime (days)
        type: text
        width: 20
        value: 1825
      - name: crl_path
        prompt: Certificate Revocation List URI
        type: text
        width: 40
      - name: crl_days
        prompt: Certificate Revocation List Expires Every (days)
        type: text
        width: 20
        value: 30
      - name: action_type
        prompt: ~
        type: hidden
        value : new_ca
      - name: update_cert_info
        prompt: ~
        type: submit
        value : Create
  new_cert:
    legend: Create New Certificate
    comments: "It's really best to do this on a local machine, and submit the CSR to pkild, but this will do in a pinch."
    fields:
      - name: cert_fqdn
        prompt: Fully Qualified Domain Name (FQDN):
        type: text
        width: 20
        value : some_distingushed_name
      - name: cert_email
        prompt: Email:
        type: text
        width: 20
        value : youremail@example.org
      - name: cert_orgunit
        prompt: Organizational Unit:
        type: text
        width: 20
        value : Some Department
      - name: cert_org
        prompt: Organization:
        type: text
        width: 20
        value : Some Company
      - name: cert_localitiy
        prompt: Locality:
        type: text
        width: 20
        value : Nashville
      - name: cert_state
        prompt: State:
        type: text
        width: 20
        value : Tennessee
      - name: cert_country
        prompt: Country:
        type: text
        width: 20
        value : US
      - name: cert_passphrase
        prompt: Private Key Pass Phrase
        type: password
        width: 20
      - name: create_certificate
        prompt: ~
        type: submit
        value : Create
      - name: action_type
        prompt: ~
        type: hidden
        value : create_cert
  my_cert:
    template: my_certificate.tt
    legend: Sign Certificate Signing Request
    fields:
      - name: csr_input
        prompt: Paste CSR
        type: textarea
        rows: 10
        cols: 64
      - name: sign_csr
        prompt: ~
        type: submit
        value : Sign
      - name: action_type
        prompt: ~
        type: hidden
        value : sign_cert
  sign:
    legend: Sign Certificate
    fields:
      - name: csr_input
        prompt: Paste CSR
        type: textarea
        rows: 10
        cols: 64
      - name: sign_csr
        prompt: ~
        type: submit
        value : Sign
      - name: action_type
        prompt: ~
        type: hidden
        value : sign_cert
    comments: "Paste the Certificate Signing Request into the box and click [Sign]"
  revoke:
    legend: Revoke Certificate
    fields:
      - name: revoke_cert
        prompt: ~
        type: submit
        value : Revoke
      - name: action_type
        prompt: ~
        type: hidden
        value : revoke_cert
    comments: "Our records indicate your have a valid Certificate.<br><br>Revoking this Certificate will render it invalid (and unusable).<br>Revoke it if you believe that your private key has been lost or compromised.<br>You will be allowed to create a new one to replace it.<br>If you have no reason to believe the key is compromised or lost, just log out."
  remove:
    legend: Remove Certificate
    fields:
      - name: remove_cert
        prompt: ~
        type: submit
        value : Remove
      - name: action_type
        prompt: ~
        type: hidden
        value : remove_cert
    comments: "<br>This will delete the certificate files from the system.<br>You will then be allowed to create a new one.<br>"
  logout:
    legend: Are you sure?
    fields:
      - name: revoke_cert
        prompt: ~
        type: submit
        value : Yes, Log Out.
      - name: logout
        prompt: ~
        type: hidden
        value : 1
  certificate_authority:
    template: ca_cert.tt
