order:
  administrator:
    - Help
    - Logout
  user:
    - Sign
    - Logout
    - Help
forms:
  new_root_ca:
    legend: Create New CA
    fields:
      - name: ca-nickname
        prompt: Name:
        type: text
        size: 20
      - name: ca-country
        prompt: Country:
        type: text
        size: 20
      - name: ca-state
        prompt: State:
        type: text
        size: 20
      - name: ca-localitiy
        prompt: Locality:
        type: text
        size: 20
      - name: ca-org
        prompt: Organization:
        type: text
        size: 20
      - name: ca-orgunit
        prompt: Organizational Unit:
        type: text
        size: 20
      - name: ca-email
        prompt: Email:
        type: text
        size: 20
      - name: update_cert_info
        prompt: ~
        type: submit
        value : Create
  new_cert:
    legend: Create New Certificate
    fields:
      - name: cert-nickname
        prompt: Name:
        type: text
        size: 20
      - name: cert-country
        prompt: Country:
        type: text
        size: 20
      - name: cert-state
        prompt: State:
        type: text
        size: 20
      - name: cert-localitiy
        prompt: Locality:
        type: text
        size: 20
      - name: cert-org
        prompt: Organization:
        type: text
        size: 20
      - name: cert-orgunit
        prompt: Organizational Unit:
        type: text
        size: 20
      - name: cert-email
        prompt: Email:
        type: text
        size: 20
      - name: update_cert_info
        prompt: ~
        type: submit
        value : Create
  openssl_cnf_prefs: 
    legend: OpenSSL Preferences
    fields:
      - name: ca_default_days
        prompt: CA Certificate lifetime (days)
        type: text
        size: 20
      - name: crl_days
        prompt: Certificate Revocation List Expires Every (days)
        type: text
        size: 20
