forms:
  new_root_ca:
    legend: Create New CA
    fields:
      - name: ca-nickname
        prompt: Name:
        type: text
        size: 20
        value: example.org
      - name: ca-country
        prompt: Country:
        type: text
        size: 20
        value: US
      - name: ca-state
        prompt: State:
        type: text
        size: 20
        value: Tennessee
      - name: ca-localitiy
        prompt: Locality:
        type: text
        size: 20
        value: Nashville
      - name: ca-org
        prompt: Organization:
        type: text
        size: 20
        value: your company
      - name: ca-orgunit
        prompt: Organizational Unit:
        type: text
        size: 20
        value: your department
      - name: ca-email
        prompt: Email:
        type: text
        size: 20
        value: sysadmins@example.org
      - name: ca-passphrase
        prompt: Private Key Pass Phrase
        type: password
        size: 20
      - name: action_type
        prompt: ~
        type: hidden
        value : new_ca
      - name: update_cert_info
        prompt: ~
        type: submit
        value : Create
  new_cert:
    legend: Create New Certificate
    comments: "It's really best to do this on a local machine, and submit the CSR to pkild, but this will do in a pinch."
    fields:
      - name: cert-nickname
        prompt: Name:
        type: text
        size: 20
        value : some_distingushed_name
      - name: cert-country
        prompt: Country:
        type: text
        size: 20
        value : US
      - name: cert-state
        prompt: State:
        type: text
        size: 20
        value : Tennessee
      - name: cert-localitiy
        prompt: Locality:
        type: text
        size: 20
        value : Nashville
      - name: cert-org
        prompt: Organization:
        type: text
        size: 20
        value : Some Company
      - name: cert-orgunit
        prompt: Organizational Unit:
        type: text
        size: 20
        value : Some Department
      - name: cert-email
        prompt: Email:
        type: text
        size: 20
        value : youremail@example.org
      - name: cert-passphrase
        prompt: Private Key Pass Phrase
        type: password
        size: 20
      - name: update_cert_info
        prompt: ~
        type: submit
        value : Create
  openssl_cnf_prefs: 
    legend: OpenSSL Preferences
    fields:
      - name: ca_default_days
        prompt: CA Certificate Lifetime (days)
        type: text
        size: 20
        value: 365
      - name: crl_days
        prompt: Certificate Revocation List Expires Every (days)
        type: text
        size: 20
        value: 30
