# yum install httpd mod_ssl mod_perl
# Add to /etc/httpd/conf.d/ssl.conf (above <VirtualHost _default_:443>)
# PerlSwitches -I/usr/share/pkild/lib
# PerlModule pkild
redwood.lab:
  domain: "root@redwood.lab"
  deploy_to: "/usr/share/pkild"
  repository: "git://github.com/fapestniegd/pkild.git"
  post_setup: "bin/local_config"
  post_deploy: "bin/local_config"
loki:
  domain: "root@loki.websages.com"
  deploy_to: "/usr/share/pkild"
  repository: "git://github.com/fapestniegd/pkild.git"
  post_setup: "bin/local_config"
  post_deploy: "bin/local_config"
