# yum install httpd mod_ssl mod_perl
# Add to /etc/http/conf.d/ssl.conf:
# PerlSwitches -I/usr/share/pkild/lib
# PerlModule pkild

redwood:
  domain: "root@redwood.lab"
  deploy_to: "/usr/share/pkild"
  repository: "git@github.com:fapestniegd/pkild.git"
  post_setup: "bin/local_config"
  post_deploy: "bin/local_config"
